site_name: AverageShiftedHistograms.jl
site_url: https://joshday.github.io/AverageShiftedHistograms.jl/
site_description: ASH estimator in Pure Julia
site_author: Josh Day

repo_name: 'GitHub'
repo_url: 'https://github.com/joshday/AverageShiftedHistograms.jl'

pages:
    - Home: index.md

docs_dir: 'docs'
site_dir: 'docs/site'

theme: 'material'

extra:
    palette:
        primary: 'indigo'
        accent: 'blue'
    author:
        github: 'joshday'
    version: 0.6.0


markdown_extensions:
    - admonition
    - codehilite(css_class=code)
    - mdx_math:
        enable_dollar_delimiter: True

extra_javascript: [
     'mathjax-config.js',
     'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'
]
